apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhands
  labels:
    app: openhands
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: openhands
  template:
    metadata:
      labels:
        app: openhands
      annotations:
        {{- if .Values.allowedUsers }}
        checksum/user-waitlist: {{ include (print $.Template.BasePath "/user-waitlist-configmap.yaml") . | sha256sum }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.allowedUsers }}
        - name: user-waitlist
          configMap:
            name: user-waitlist
        {{- end }}
        - name: keycloak-config-script
          configMap:
            name: keycloak-config-script
            defaultMode: 0755
      initContainers:
      - name: keycloak-config
        imagePullPolicy: Always
        image: '{{.Values.image.repository}}:{{.Values.image.tag | default .Chart.AppVersion }}'
        env:
        {{- include "openhands.env" . | nindent 8 }}
        volumeMounts:
        - name: keycloak-config-script
          mountPath: /scripts
        command:
          - sh
          - /scripts/keycloak-config.sh
      containers:
      - name: openhands
        imagePullPolicy: Always
        image: '{{.Values.image.repository}}:{{.Values.image.tag | default .Chart.AppVersion }}'
        command: ["/bin/sh"]
        args:
          - "-c"
          - "exec {{- if .Values.datadog.enabled }} ddtrace-run {{- end }} uvicorn {{ if eq .Values.appConfig.OPENHANDS_CONFIG_CLS "openhands.server.config.server_config.ServerConfig" }}openhands.server.app:app{{ else }}saas_server:app{{ end }} --host 0.0.0.0 --port 3000 --workers {{ .Values.uvicorn.workers }}"
        ports:
        - containerPort: 3000
        resources:
          {{- toYaml .Values.deployment.resources | nindent 12 }}
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
          {{- if .Values.allowedUsers }}
          - name: user-waitlist
            mountPath: /app/user-waitlist
          {{- end }}
        env:
        {{- include "openhands.env" . | nindent 8 }}
